name: Generate GitHub Contribution Snake

on:
  # Har roz raat 12 baje chalega
  schedule:
    - cron: "0 0 * * *"
  
  # Manually run karne ke liye
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      # Repo checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate snake SVG
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Dev-akash77
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Push generated SVGs to output branch
      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
